### ISSUE TITLE
Request: Subdirectories

### ISSUE THREAD

**Issue by arronhunt** [tsimenis/figma-export-icons#1]
In our design system we categorize our icons by type. For example `Arrows / Left Arrow.svg`. It would be a great addition if this script could parse file names as folders and export them appropriately.

**Comment by tsimenis** [comment]
Hey @arronhunt,

that's a valid request, I will look into it.

**Comment by tsimenis** [comment]
Updated in [latest release](https://github.com/tsimenis/figma-export-icons/releases/tag/v1.1.0), also available in npm.

I hope this works as you expected @arronhunt
