### ISSUE TITLE
Multiple frames and pages

### ISSUE THREAD

**Issue by yceballost** [tsimenis/figma-export-icons#14]
Hi!

Could I export at the same time 3 different frames (I have 3 icon weights)?

And multiple frames and pages? I have in the same file a multibrand icon system

Thanks!

**Comment by tsimenis** [comment]
Hi!

You could easily solve your first problem by moving your 3 icon weights in one frame, unless there is a reason you cannot do that. Still that is not something the script should be responsible for.

You can export using different config files `--config=path/to/config.json` as long as they have different `iconsPath` to export to.

**Comment by yceballost** [comment]
Thanks! works perfectly!
