### ISSUE TITLE
Export icons without root frame "icons"

### ISSUE THREAD

**Issue by mikeozornin** [tsimenis/figma-export-icons#5]
We use your great package to create icon fonts from figma. It help us a lot.

Is it possible to export icons from page itself without additional frame "icons"? Do I need to create pull request with this change?

**Comment by tsimenis** [comment]
@mikeozornin glad to hear it helps!

Hmm, fetching icons from the page should be possible. 
But wouldn't you always create a frame? I'm just trying to first understand the use case and if this makes sense to be solved from the package or directly in figma.

if you can provide me with your use case that'd be great

**Comment by mikeozornin** [comment]
Usually we have a separate page for icons, every icon is a root page frame. So we need to export every frame on that page as SVG.

This way of organising is just more convenient for us. Root frames icons could be easily rearranged by name with Figma Format plugin. If icons are combined to some frame we have to unframe them, rearrange and frame again. It creates a lot of changes during publish.

**Comment by tsimenis** [comment]
Ah ok that makes sense. 

Do you want to create a pull request for this?

Otherwise I can look into it when I have some free time.

**Comment by mikeozornin** [comment]
I really not sure I could create, I'm not very good developer. But I can try to implement it and create PR.

**Comment by mikeozornin** [comment]
I create a small patch for myself, will try to test it in our team as workaround.

**Comment by TomasFuentes** [comment]
Hello!,
I'm having the same problem. I tried with the solution of @mikeozornin and it worked perfectly on my figma file. Thanks

**Comment by tsimenis** [comment]
Hey @mikeozornin  and @TomasFuentes this feature has been added in #6 and published a new version.
