### ISSUE TITLE
Add support for frames nested within groups

### ISSUE THREAD

**Issue by pbilyk** [tsimenis/figma-export-icons#9]
I ran into an issue when we started implementing the atomic design principles on our project and grouped our frames by levels.

This resulted in the icon export tool breaking because the Icons frame was now not a direct descendant of a page, but a child in the 'atoms' group.

I have opened a [Pull Request](https://github.com/tsimenis/figma-export-icons/pull/8) with the fix for this issue for your consideration 🙂

**Comment by tsimenis** [comment]
Hi @pbilyk 

could you give me an example on how your figma file structure looks like? I believe I understand the issue but I want to make sure we are on the same page. 

I've seen the PR, ideally I don't want to introduce more options in the config but first I need to understand the your use case.

**Comment by pbilyk** [comment]
Hi George, thanks for getting back on this.

So, basically what we have is a separate page with the design system, where we gather the UI components based on the atomic design principle.

On this page we have a group with "atoms", in which we have the frame that contains icons. So it basically is nested on second level.

I decider to add a separate option that would allow us to specify the deeper nesting for the frame.

We could add this as an extension of the existing option, but I'm not sure if it will not introduce any other issues for current users of the package.

Let me know of this makes sense, because English is not my first language 😅

**Comment by tsimenis** [comment]
As I mentioned previously I'd prefer not adding extra options to the config. I've updated the PR to be able to pass a path for frame in the config.

Now both `frame="Icons"` and `frame="Path/to/Icons` should work.

**Comment by pbilyk** [comment]
Great! Thanks for merging this, works perfectly for me :)
